--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: pgadmin
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: pgadmin
  template: 
    metadata: 
      labels: 
        app: pgadmin
    spec: 
      containers: 
        - 
          env: 
            - 
              name: PGADMIN_DEFAULT_EMAIL
              value: admin
            - 
              name: PGADMIN_DEFAULT_PASSWORD
              value: admin
            - 
              name: PGADMIN_PORT
              value: "80"
          image: dpage/pgadmin4
          name: pgadmin4
          ports: 
            - 
              containerPort: 80
              name: pgadminport
